import cv2 as cv
img=cv.imread('Batman.png')
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
cv.imshow('BATMAN',img)
#cv.imshow('BATMAN',gray)
blur = cv.GaussianBlur(gray, (3, 3), cv.BORDER_DEFAULT)
#cv.imshow('BATMA',blur)
canny = cv.Canny(img,125,175)
#cv.imshow('bat', canny)
dilated = cv.dilate(canny, 3, 3, itterations = 1)
eroded = cv.erode(dilated, 3, 3, itterations = 1)
cv.imshow('erode', eroded)
#cv.imshow('dilate', dilated)
cv.waitKey(0)